// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\Qiu_YQ\subsystem.v
// Created: 2021-11-15 00:21:48
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.001
// Target subsystem base rate: 0.001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// output_rsvd                   ce_out        0.001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subsystem
// Source Path: Qiu_YQ/subsystem
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subsystem
          (clk,
           reset_x,
           clk_enable,
           input_rsvd,
           ce_out,
           output_rsvd);


  input   clk;
  input   reset_x;
  input   clk_enable;
  input   signed [15:0] input_rsvd;  // sfix16_En11
  output  ce_out;
  output  signed [15:0] output_rsvd;  // sfix16_En24


  wire signed [63:0] IIR_High_pass_Filter_fix_point_p_out1;  // sfix64_En39


  IIR_High_pass_Filter_fix_point_p u_IIR_High_pass_Filter_fix_point_p (.clk(clk),
                                                                       .reset_x(reset_x),
                                                                       .enb(clk_enable),
                                                                       .Input_rsvd(input_rsvd),  // sfix16_En11
                                                                       .Output_rsvd(IIR_High_pass_Filter_fix_point_p_out1)  // sfix64_En39
                                                                       );

  assign output_rsvd = IIR_High_pass_Filter_fix_point_p_out1[30:15];



  assign ce_out = clk_enable;

endmodule  // subsystem

